### ISSUE TITLE
Error messages "mod_entry is nil and cover = .."

### ISSUE THREAD

**Issue by cjimison** [alfert/coverex#18]
We use the library amnesia which does some macro tricks to make using mnesia easier.  However when I run coverex on it get a errors about mod_entry is nil.  It would be nice to suppress these errors because it looks like the test is failing and the are not.  Also the coverage reports are generating as well.

Example error:

15:31:55.002 [error] mod_entry is nil and cover = [{{Database.Builds.App, 0}, 0}, {{Database.Builds.App, 0}, 3}, {{Database.Builds.App, 0}, 0}, {{Database.Builds.App, 0}, 0}, {{Database.Builds.App, 0}, 1}, {{Database.Builds.App, 0}, 0}, {{Database.Builds.App, 0}, 0}, {{Database.Builds.App, 0}, 0}, {{Database.Builds.App, 0}, 1}, {{Database.Builds.App, 0}, 0}, {{Database.Builds.App, 0}, 0}, {{Database.Builds.App, 0}, 0}, {{Database.Builds.App, 0}, 2}, {{Database.Builds.App, 0}, 0}, {{Database.Builds.App, 0}, 0}, {{Database.Builds.App, 0}, 0}, {{Database.Builds.App, 0}, 0}, {{Database.Builds.App, 0}, 0}, {{Database.Builds.App, 0}, 0}, {{Database.Builds.App, 15}, 0}, {{Database.Builds.App, 15}, 0}, {{Database.Builds.App, 15}, 1}, {{Database.Builds.App, 15}, 1}, {{Database.Builds.App, 15}, 0}, {{Database.Builds.App, 15}, 0}, {{Database.Builds.App, 15}, 0}, {{Database.Builds.App, 15}, 0}, {{Database.Builds.App, 15}, 0}, {{Database.Builds.App, 15}, 0}, {{Database.Builds.App, 15}, 0}, {{Database.Builds.App, 15}, 0}, {{Database.Builds.App, 15}, 0}, {{Database.Builds.App, 15}, 1}, {{Database.Builds.App, 15}, 0}, {{Database.Builds.App, 15}, 0}, {{Database.Builds.App, 15}, 0}, {{Database.Builds.App, 15}, 0}, {{Database.Builds.App, 15}, 0}, {{Database.Builds.App, 15}, 0}, {{Database.Builds.App, 15}, 0}, {{Database.Builds.App, 15}, 0}, {{Database.Builds.App, 15}, 0}, {{Database.Builds.App, 15}, 0}, {{Database.Builds.App, 15}, 0}, {{Database.Builds.App, 15}, 0}, {{Database.Builds.App, 15}, 0}, {{Database.Builds.App, 15}, 0}, {{Database.Builds.App, ...}, 0}, {{...}, ...}, {...}, ...]

15:31:55.019 [error] mod_entry is nil and cover = [{{Database.Builds, 0}, 0}, {{Database.Builds, 0}, 0}, {{Database.Builds, 0}, 1}, {{Database.Builds, 0}, 0}, {{Database.Builds, 0}, 0}, {{Database.Builds, 0}, 0}, {{Database.Builds, 0}, 0}, {{Database.Builds, 1}, 0}, {{Database.Builds, 1}, 0}, {{Database.Builds, 6}, 1}, {{Database.Builds, 6}, 0}, {{Database.Builds, 6}, 1}, {{Database.Builds, 6}, 2}, {{Database.Builds, 6}, 0}, {{Database.Builds, 6}, 0}, {{Database.Builds, 6}, 0}, {{Database.Builds, 6}, 0}, {{Database.Builds, 6}, 0}, {{Database.Builds, 6}, 2}]

**Comment by cjimison** [comment]
Link to amnesia
https://github.com/meh/amnesia

**Comment by alfert** [comment]
Yeah, this is really ugly. I will change this.

**Comment by cjimison** [comment]
Just pulled the new changes and it looks great.  Thanks!

**Comment by alfert** [comment]
coverex 1.4.6 is out.
