### ISSUE TITLE
I can't run tests with coverage

### ISSUE THREAD

**Issue by es1o** [alfert/coverex#29]
Hello. I'm trying to add coverage to my elixir project but I have a problem:

```
~/work/user(branch:master*) » mix test --cover
Coverex compiling modules ... 
compile_path is "/home/user/work/app/_build/test/lib/app/ebin"
Options are: [output: "cover", tool: Coverex.Task]
** (UndefinedFunctionError) function :cover.start/0 is undefined (module :cover is not available)
    :cover.start()
    lib/coverex/task.ex:23: Coverex.Task.start/2
    (mix) lib/mix/tasks/test.ex:193: Mix.Tasks.Test.run/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

I have the same problem when I download coverex code and run mix task --cover
I was looking into code and I wasn't able to find problem.

**Comment by alfert** [comment]
It looks like you don't have the cover application available. Cover is the work horse and is part of Erlang/OTP. Could it be that you don't have the entire Erlang/OTP distribution installed? What version of Elixir and Erlang do you use?

**Comment by es1o** [comment]
Hi! Sorry for delayed response.

I've reinstalled elixir and it works...

**Comment by hvnsweeting** [comment]
If you using Ubuntu 18.04, this would help install `cover`

```
 sudo apt-get install -y erlang-tools
```
