### ISSUE TITLE
Nonsensical results when posting to Coveralls via Travis

### ISSUE THREAD

**Issue by scouten** [alfert/coverex#34]
If you look at any of the coverage reports at https://coveralls.io/github/scouten/sqlite_ecto2, the lines reported as covered vs not covered (even executable vs not) appear to be almost completely random.

One particularly crazy example is https://coveralls.io/builds/9415936/source?filename=lib%2Fsqlite_ecto%2Fquery.ex, in which lines 117 and 119 are shown as being hit multiple times, but line 121 is missed. All three of those lines are comments.

When I look at HTML results for the same file generated locally (not on Coveralls), the results look reasonable. (I haven't analyzed line-by-line, but it looks at least credible.)

**Comment by alfert** [comment]
Fixed in 1.4.11 - Thanks!
